log_level = "warn"
outputs = { Targets = ["eDP-1"] }
position = "Top"
app_launcher_cmd = "walker"

[modules]
left = [ [ "appLauncher", "Updates","zed","Workspaces" ] ]
#left = [["Updates","Workspaces"]]
center = [ "WindowTitle" ]
right = [ "SystemInfo", [  "Tray", "Clock", "Privacy", "Settings" ] ]

[clock]
format = "%D %r"
[updates]
check_cmd = "checkupdates; yay -Qua"
#update_cmd = 'kitty -e bash -c "yay ; echo Done - Press enter to exit; read" &'
update_cmd = ''
[workspaces]
enable_workspace_filling = true

[[CustomModule]]
name = "appLauncher"
icon = "ó±—¼"
command = "wofi --show drun"

#[[CustomModule]]
#name = "zed"
#icon = "zed"
#command = ''

[system_info]
indicators = [ {Disk = "/home/retsam"},"Cpu", "Memory", "Temperature" ,"IpAddress"]

[system_info.cpu]
warn_threshold = 60
alert_threshold = 80

[system_info.memory]
warn_threshold = 70
alert_threshold = 85

[system_info.disk]
warn_threshold = 80
alert_threshold = 90

[system_info.temperature]
warn_threshold = 60
alert_threshold = 80

[window_title]
truncate_title_after_length = 100
mode ="Title"
[settings]
#lock_cmd = "playerctl --all-players pause; nixGL hyprlock &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"
remove_airplane_btn = true
remove_idle_btn =true

#bluetooth_more_cmd = "blueberry"

[appearance]

success_color = "#a6e3a1"
text_color = "#cdd6f4"

workspace_colors = [ "#fab387", "#b4befe", "#cba6f7" ]

[appearance.primary_color]
base = "#fab387"
text = "#1e1e2e"

[appearance.danger_color]
base = "#f38ba8"
weak = "#f9e2af"

[appearance.background_color]
base = "#1e1e2e"
weak = "#313244"
strong = "#45475a"

[appearance.secondary_color]
base = "#11111b"
strong = "#1b1b25"
